### ISSUE TITLE
Outgunned under v12.328

### ISSUE THREAD

**Issue by NerdEyeIndustries** [Genii-Locorum/outgunned#3] opened 2024-07-04 01:40 UTC
Permissions for players seem totally messed.. Here's a list of things they can't do we've discovered so far:

1. Create Actors (even when in User Permissions all of this is set)
2. Edit Items on the sheet. Gear is the best example. They can create an item but not edit its title (on the window) or see the mag glass to edit it off their sheet.

I've mitigated #1 by creating a character entry for them, but #2 really cramps our style...

Thanks..

**Comment by Genii-Locorum** [comment] 2024-07-04 13:52
Heya

Issue 1 - I think this is a Foundry issue, not an Outgunned issue (although there is probably a way to code a solution).  If you go in to Foundry > Game Settings > User Management > Configure Permissions you can set it so players can create actors/

Issue 2 - I've got a fix ready so players can edit Gear, Gun, Ride, Experience names.  The other items I'm proposing to restrict to GMs as these are things that are game settings.  

Let me run it past my co-authors and hopefully this can be released quickly.

**Comment by NerdEyeIndustries** [comment] 2024-07-04 15:07
On Issue 1, I've set those permissions already and still no create entitlements for players as described.

**Comment by Genii-Locorum** [comment] 2024-07-05 04:56
Thanks - Issue 2 I've released a new update (Beta 2) - please let me know if this fixes it.

Issue 1 - I've tested this without modules and it works for me.  What modules are you using and do you still get the issue if you deactivate them.   If it's a module conflict I may have a lead on the problem and will do more testing when I'm home on Monday.

Do you self host or does someone else host for you?  Just trying to think of permissions areas and what the system may be interacting with to narrow down the problem.

Cheers

Simon

**Comment by NerdEyeIndustries** [comment] 2024-07-05 14:19
Host myself, as I run the NODE.JS version on my own in-home server. With no modules active, here's what I get as a player when attempting to create a character: 

![image](https://github.com/Genii-Locorum/outgunned/assets/103020066/c5fff73a-30ca-40ee-85e3-1c66761a35f7)

**Comment by NerdEyeIndustries** [comment] 2024-07-06 03:23
Ok, the permissions issue has now shown up in Pathfinder, so clearly its a Foundry issue....

**Comment by Genii-Locorum** [comment] 2024-07-08 15:03
The error is logged on Foundry Github - https://github.com/foundryvtt/foundryvtt/issues/11311

I will keep the issue open until it's fixed and will aim to test when it gets patched.

**Comment by NerdEyeIndustries** [comment] 2024-07-10 20:48
Running 2.03 now, the player can create & edit (via the popup) but after that, no edit possible other than to delete. Here's my test player and his sheet:
![image](https://github.com/Genii-Locorum/outgunned/assets/103020066/a855e920-89a6-415f-8d44-552b8ba26f63)
Is this by design? I'll just make sure to warn my players before they start editing items..

**Comment by NerdEyeIndustries** [comment] 2024-07-10 20:50
Additionally, player cannot edit cost on the item/gear window:
![image](https://github.com/Genii-Locorum/outgunned/assets/103020066/290c882b-4c33-41da-bfd5-2c70ce1a9881)

**Comment by NerdEyeIndustries** [comment] 2024-07-10 20:53
Additional, additional: if I LOCK the sheet then the magnifying glass appears and I can edit all values on the item/gear popup.. Again, by design?

Thanks!

**Comment by Genii-Locorum** [comment] 2024-07-14 07:17
New release (2.04) will allow players to edit all data points for Guns, Rides and Gear - hopefully this resolves the issues you've flagged (but please let me know if they don't - I won't close this until you say so).

Locking the sheet then opening the item via the magnifying glass will allow you to edit all values (so yes, by design) - it would be possible to code it so that you can only edit an item that is on a character sheet if the character is unlocked if there is a need for this.

**Comment by NerdEyeIndustries** [comment] 2024-07-15 05:02
2.04 solves the edit issue, thanks.

**Closed** 2024-07-21 05:58 UTC
